version: 2
jobs:
  build:
    branches:
      only:
      - master
      - feature/ingress-api-update
    docker:
    - image: docker:18.06
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: docker-hub
        environment:
        - DOCKERHUB_REPO: jchudb93
        command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD; set -x; for repo in "livy-spark"; do for script in $(find ./$repo/ -name build.sh); do if [ -n $script ]; then $script; fi; done; done
